2017/04/24 13:10:31 [error] [exception.CException] CException: CAssetManager.basePath "/var/www/html/testapp/assets" is invalid. Please make sure the directory exists and is writable by the Web server process. in /var/www/html/yii_framework/framework/web/CAssetManager.php:138
Stack trace:
#0 /var/www/html/yii_framework/framework/web/CAssetManager.php(123): CAssetManager->setBasePath('/var/www/html/t...')
#1 /var/www/html/yii_framework/framework/web/CAssetManager.php(217): CAssetManager->getBasePath()
#2 /var/www/html/yii_framework/framework/gii/GiiModule.php(143): CAssetManager->publish('/var/www/html/y...')
#3 /var/www/html/yii_framework/framework/base/CComponent.php(111): GiiModule->getAssetsUrl()
#4 /var/www/html/yii_framework/framework/base/CModule.php(105): CComponent->__get('assetsUrl')
#5 /var/www/html/yii_framework/framework/gii/views/layouts/main.php(5): CModule->__get('assetsUrl')
#6 /var/www/html/yii_framework/framework/web/CBaseController.php(126): require('/var/www/html/y...')
#7 /var/www/html/yii_framework/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/y...', Array, true)
#8 /var/www/html/yii_framework/framework/web/widgets/CContentDecorator.php(76): CBaseController->renderFile('/var/www/html/y...', Array, true)
#9 /var/www/html/yii_framework/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate('<div class="con...')
#10 /var/www/html/yii_framework/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput('<div class="con...')
#11 /var/www/html/yii_framework/framework/web/CBaseController.php(215): COutputProcessor->run()
#12 /var/www/html/yii_framework/framework/web/CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#13 /var/www/html/yii_framework/framework/gii/views/layouts/column1.php(7): CBaseController->endContent()
#14 /var/www/html/yii_framework/framework/web/CBaseController.php(126): require('/var/www/html/y...')
#15 /var/www/html/yii_framework/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/html/y...', Array, true)
#16 /var/www/html/yii_framework/framework/web/CController.php(787): CBaseController->renderFile('/var/www/html/y...', Array, true)
#17 /var/www/html/yii_framework/framework/gii/controllers/DefaultController.php(47): CController->render('login', Array)
#18 /var/www/html/yii_framework/framework/web/actions/CInlineAction.php(49): DefaultController->actionLogin()
#19 /var/www/html/yii_framework/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#20 /var/www/html/yii_framework/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#21 /var/www/html/yii_framework/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#22 /var/www/html/yii_framework/framework/web/CWebApplication.php(282): CController->run('login')
#23 /var/www/html/yii_framework/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#24 /var/www/html/yii_framework/framework/base/CApplication.php(185): CWebApplication->processRequest()
#25 /var/www/html/testapp/index.php(13): CApplication->run()
#26 {main}
REQUEST_URI=/testapp/index.php?r=gii/default/login
---
2017/04/24 13:22:56 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: could not find driver in /var/www/html/yii_framework/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii_framework/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii_framework/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii_framework/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii_framework/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii_framework/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii_framework/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii_framework/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii_framework/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii_framework/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii_framework/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii_framework/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii_framework/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii_framework/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii_framework/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii_framework/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/testapp/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testapp/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/testapp/index.php?r=gii/default/index
---
2017/04/24 13:25:56 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'testdrive' in /var/www/html/yii_framework/framework/db/CDbConnection.php:399
Stack trace:
#0 /var/www/html/yii_framework/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /var/www/html/yii_framework/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /var/www/html/yii_framework/framework/base/CModule.php(394): CDbConnection->init()
#3 /var/www/html/yii_framework/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /var/www/html/yii_framework/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /var/www/html/yii_framework/framework/web/CFormModel.php(39): ModelCode->init()
#6 /var/www/html/yii_framework/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /var/www/html/yii_framework/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /var/www/html/yii_framework/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /var/www/html/yii_framework/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /var/www/html/yii_framework/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/html/yii_framework/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/html/yii_framework/framework/web/CWebApplication.php(282): CController->run('index')
#13 /var/www/html/yii_framework/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /var/www/html/yii_framework/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /var/www/html/testapp/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/testapp/index.php?r=gii/model/index
HTTP_REFERER=http://localhost/testapp/index.php?r=gii/default/index
---
2017/04/24 13:32:14 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "user". in /var/www/html/yii_framework/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/html/yii_framework/framework/web/CWebApplication.php(141): CWebApplication->runController('user')
#1 /var/www/html/yii_framework/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /var/www/html/testapp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/testapp/index.php?r=user
---
